version: '3.6'
services:
  kwelidb:
    image: mysql:5.7.21
    restart: always
    volumes:
      - kwelismart:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "kweli"
      MYSQL_USER: "kwelismart"
      MYSQL_PASSWORD: "kwelismart"
      MYSQL_HOST: "localhost"
  kwelios:
    container_name: kwelios
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:   # Binds volume to enable working through docker locally
      - type: bind
        source: ./src/
        target: /app/src/
      - type: bind
        source: ./package.json
        target: /app/package.json
      - type: bind
        source: ./tsconfig.json
        target: /app/tsconfig.json
    depends_on:
      - kwelidb
    ports:
      - 3000:3000
    environment: 
      PORT: 3000
      NODE_ENV: "local"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "kweli"
      MYSQL_USER: "kwelismart"
      MYSQL_PASSWORD: "kwelismart"
      MYSQL_HOST: "localhost"
      MYSQL_PORT: 3306
    network_mode: "host"
volumes:
  kwelismart: