version: '3.2'

services:
  kweli:
    container_name: kweli
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:   # Binds volume to enable working through docker locally
      - type: bind
        source: ./src/
        target: /app/src/
      - type: bind
        source: ./package.json
        target: /app/package.json
      - type: bind
        source: ./tsconfig.json
        target: /app/tsconfig.json
    ports:
      - 3000:3000
    environment: 
      PORT: 3000