version: '3.6'

services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=kwelismart
      - POSTGRES_PASSWORD=kwelismart
      - POSTGRES_DB=kwelidb
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  kweli:
    container_name: kweli
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:   # Binds volume to enable working through docker locally
      - type: bind
        source: ./src/
        target: /app/src/
      - type: bind
        source: ./package.json
        target: /app/package.json
      - type: bind
        source: ./tsconfig.json
        target: /app/tsconfig.json
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment: 
      PORT: 3000
  
volumes:
  postgres: